.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH list 1  "list " 
.SH NAME
list \- List available drives
.SH SYNOPSIS
\fBlist\fR [\fB\-a\fR|\fB\-\-all\fR] [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List available drives
.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-all\fR
Show all drives including system drives
.TP
\fB\-\-json\fR
Output in JSON format
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
